export const SHARED_ERROR_CODES = {
  USER_INSERT_FAILED:        'USER_INSERT_FAILED',
  FOREIGN_KEY_VIOLATION:     'FOREIGN_KEY_VIOLATION', 
  NOT_NULL_VIOLATION:        'NOT_NULL_VIOLATION',  
} as const;